### ISSUE TITLE
Response error handling

### ISSUE THREAD

**Issue by jmassardo** [jmassardo/issues-to-totango#7]
When something bad happens in the communication with Totango, we don't handle the error well...

We should capture the common errors and display a friendly message to the user while still providing a failure exit code.

Example:
```/home/runner/work/_actions/jmassardo/issues-to-totango/main/index.js:71
    touchpoint_id = (JSON.parse(response.body))["note"]["id"]
                                                       ^

TypeError: Cannot read property 'id' of undefined
    at Request._callback (/home/runner/work/_actions/jmassardo/issues-to-totango/main/index.js:71:56)
    at Request.self.callback (/home/runner/work/_actions/jmassardo/issues-to-totango/main/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/home/runner/work/_actions/jmassardo/issues-to-totango/main/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/home/runner/work/_actions/jmassardo/issues-to-totango/main/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by collinmcneese** [comment]
Updates to logic wrap functions in try/catch logic now
